Radio Update - Additional Classes added, Documentation in progress, Tests in progress
CSC207-2022F-UofT/course-project-shazamify pull request #116
Opened 2022-12-05 19:05 UTC by cynthiaxsa

Pushing my current progress in the Radio Feature. Many aspects of it are uncompleted, though hopefully this gives everyone a better idea of what I am currently working towards. In this patch, I have done a few of the following:

- Added documentation and TODOs throughout 
- Readjusted the structure of my classes, added several needed additional classes especially along the IA level. 
- Completed the Radiosearch use case for the search engine - yet to be tested. 
- Set up the skeleton of the tests that I am planning on implementing in the future. 

A note! At the stage it is currently at, Radio is not heavily involved or otherwise dependent on other features. There should not be many issues or concerns needed on that front, but if there are any do let me know!

2022-12-05 19:41 UTC, Starliyiyu commented on src/main/java/abr/radio_abr/RadioStationInputBoundary.java
> +import interface_adaptors.radio_ia.RadioPlayerViewModel;
abr depending on ia

2022-12-05 19:44 UTC, varygx requested changes
Please pull from main and merge the changes into your branch. There's a lot of files unrelated to your PR that are being changed. For example, I'm seeing a test class being reverted to a very old version.

2022-12-05 19:48 UTC, Starliyiyu commented on src/main/java/abr/search_engine_abr/SearchUserAbr.java
> +import abr.user_avatar_image_management_abr.ds.user_search_engine.SearchEngineFileGateway;
there would be package arrangement problems if this line runs no problem; if you are trying to import search engine gateways, import  SearchEngineDatabaseGateway instead, the filegateway is a class in ia & violates clean architecture

2022-12-05 19:50 UTC, Starliyiyu approved these changes
some import statements seem weird, not sure if this is because your local repo didn't update to the latest version, everything else looks good

2022-12-06 03:07 UTC, 2368883029 requested changes
You should solve these problems by 
1) move .ds directory out of abr.userAvatarManagement directory
2) pull changes from the main, and preserve UserLogUI from the Main manually by resolving conflicts.

2022-12-06 03:07 UTC, 2368883029 commented on src/main/java/framework/user_screen/UserLogUI.java
>      }
This file is the old version of the UserLogUI, please preserve the newer version in Main Branch

2022-12-06 03:07 UTC, 2368883029 commented on src/main/java/abr/user_avatar_image_management_abr/ds/user_database/UserFileReader.java
> +package abr.user_avatar_image_management_abr.ds.user_database;
There seems to be a FileArrangement problem, ds File is now under ABR.

2022-12-07 19:20 UTC, cynthiaxsa commented on src/main/java/abr/radio_abr/RadioStationInputBoundary.java
> +import interface_adaptors.radio_ia.RadioPlayerViewModel;
Gotcha, I've adjusted it now!

2022-12-07 19:23 UTC, cynthiaxsa commented
With assistance from Allen I've been able to update my branch properly, so it should now have all files up to date. I'm going to re-push now!

2022-12-07 19:51 UTC, cynthiaxsa commented
Closing for now as I figure this out

2022-12-07 19:51 UTC, closed without merging